### ISSUE TITLE
The Time to Open source 

### ISSUE THREAD

**Issue by leon-liangwu** [LifengFan/Human-Gaze-Communication#2]
Hi, @LifengFan, are you still working on opening source the code and the data? 
Could you please kindly let me know when will you do this?

**Comment by LifengFan** [comment]
> Hi, @LifengFan, are you still working on opening source the code and the data?
> Could you please kindly let me know when will you do this?

Yes, still working on it and doing final check. We met some legal issues. Hopefully, we can work out in the coming month. Thanks.

**Comment by leon-liangwu** [comment]
@LifengFan Thanks.
